typography_spectrum: 0.82818
color:
  brandColors:
    - '#c9dbe9'
    - '#242834'
    - '#7695b2'
    - '#6f7782'
    - '#495062'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.039013577392324805
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.70785
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Rainer Sax
  email: rainer.sax@gmail.com
name: Rainer Sax
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Rainer Sax
purpose: []
